baseURL = ''
languageCode = 'en-us'
title = 'FirewallChronicles'
theme = 'risotto'
author = 'Dennis Sarovski'
copyright = '© [Dennis Sarovski](https://firewallchronicles.com) & [risotto contributors](https://github.com/joeroe/risotto/graphs/contributors).'
paginate = 3
DefaultContentLanguage = 'en'
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ['error-remote-getjson']

# Automatically add content sections to main menu
sectionPagesMenu = 'main'

[params]
noindex = false

[params.theme]
palette = 'base16-dark'

# Sidebar: about/bio
[params.about]
title = 'Welcome'
description = '01/11/23 Welcome to my site. You can check out more details about me below by clicking the social media buttons.'
logo = 'images/logo-2.png'



# Sidebar: social links
# Available icon sets:
# * FontAwesome 6 <https://fontawesome.com/> ('fa-brands', 'fa-normal', or 'fa-solid' for brands)
# * Academicons <https://jpswalsh.github.io/academicons> ('ai ai-')

[[params.socialLinks]]
icon = 'fa-brands fa-github'
title = 'GitHub'
url = 'https://github.com/capactiyvirus'

[[params.socialLinks]]
icon = 'fa-solid fa-envelope'
title = 'Email'
url = 'mailto:example@example.com'

# [[params.socialLinks]]
# icon = 'ai ai-orcid'
# title = 'ORCID'
# url = 'https://orcid.org/0000-0001-2345-6789'

[menu]
  [[menu.main]]
    identifier = 'about'
    name = 'About'
    pageRef = '/about'
    weight = 10
  [[menu.main]]
    identifier = 'posts'
    name = 'Posts'
    pageRef = '/posts'
    weight = 20
  
  [[menu.main]]
    identifier = 'who ami i'
    name = 'Who Am I'
    pageRef = '/who-am-i'
    weight = 30
  [[menu.main]]
    identifier = 'archives'
    name = 'Archives'
    pageRef = '/archives'
    weight = 40
    

[posts]
  [[posts.main]]
    identifier = 'how i ate'
    name = 'Ate'
    pageRef = '/posts/how-i-at-shit/'
    weight = 1

[taxonomies]
category = 'categories'
tag = 'tags'
series = 'series'

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[markup]

  # Table of contents
  # Add toc = true to content front matter to enable
  toc = true
  [markup.tableOfContents]
    toc = true
    startLevel = 2
    endLevel   = 3
    ordered    = true

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true